name: Tufuwu/test2
on:
  push:
    branches:
    - "**/*"
  pull_request:
#   # This item has no matching transformer
#   maximum_number_of_builds: 0
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: "${{ matrix.python }}"
    - name: Set up pip cache
      uses: actions/cache@v3.3.2
      with:
        path: "~/.cache/pip"
        key: "${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}"
        restore-keys: "${{ runner.os }}-pip-"
    - run: make travis-setup
    - run: make ci
    strategy:
      matrix:
        PYTHONHASHSEED:
        - '0'
        python:
        - '3.8'
        - '3.8'
        - '3.8'
        - '3.9'
    env:
      PYTHONHASHSEED: "${{ matrix.PYTHONHASHSEED }}"
  test_pypy:
    needs:
    - test
    runs-on: ubuntu-22.04
    env:
      PYTHONHASHSEED: '0'
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Set up pip cache
      uses: actions/cache@v3.3.2
      with:
        path: "~/.cache/pip"
        key: "${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}"
        restore-keys: "${{ runner.os }}-pip-"
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: pypy-3.6
    - run: pip install termcolor==1.1.0 pytest==6.2.4 pytest-xdist==2.3.0 dataclasses==0.8
    - run: py.test -n auto
  coverage:
    needs:
    - test
    - test_pypy
    runs-on: ubuntu-22.04
    env:
      PYTHONHASHSEED: '0'
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Set up pip cache
      uses: actions/cache@v3.3.2
      with:
        path: "~/.cache/pip"
        key: "${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}"
        restore-keys: "${{ runner.os }}-pip-"
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.9'
    - run: make travis-setup
    - run: make coverage
    - run: bash <(curl -s https://codecov.io/bash)
      if: "${{ success() }}"
