name: Tufuwu/test2
on:
  push:
    branches:
    - "**/*"
    - main
  pull_request:
#   # This item has no matching transformer
#   maximum_number_of_builds: 0
jobs:
  Flake8:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.8'
    - run: pip install flake8
    - run: flake8
  Dockerfile_lint:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.8'
    - run: docker run -i hadolint/hadolint:v1.19.0-45-gef91156-alpine < Dockerfile
    services:
#       # This item has no matching transformer
#       docker:
