name: Tufuwu/test2
on:
  push:
    branches:
    - "**/*"
  pull_request:
#   # This item has no matching transformer
#   maximum_number_of_builds: 0
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: "${{ matrix.python }}"
    - run: pip install -r requirements.txt
    - run: pip install -r tests/requirements.txt
    - run: python setup.py -q install
    - run: nosetests --with-coverage --cover-package=btcde
    - run: codecov
      if: "${{ success() }}"
    strategy:
      matrix:
        python:
        - '3.8'
        - '3.8'
        - '3.9'
  Test_Release:
    needs:
    - test
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.8'
    - run: pip install -r requirements.txt
    - run: pip install -r tests/requirements.txt
    - run: python setup.py -q install
    - run: nosetests --with-coverage --cover-package=btcde
#     # This item has no matching transformer
#     - pypi:
#         provider: pypi
#         server: https://test.pypi.org/legacy/
#         user: __token__
#         password:
#           secure: h/wc+642BHl/T7zlgH3.8fbpp7lttVLd13yIwJoi+YAXuZiX/w5fd2uQNnr3Kh9JAaaM2ZXDpn0Xo8y7gq8pmrrQ0IMy6Df4rKUkznLXxNt3/1yLuXGPLrBESoPUM0HRqJIUBwrJuEFS4JrKaHPf018li7+/Re93MSDPKhXSaJhzVFiwmCVDpeNWptREnrfE0FqzY+dq//w+Tac/ABp+oFTQ/IVfg1atxJbxk0sErG6CAImCOYA4mxDhBeFcJC+03jRCazHmPjrDGHjktRVU2s1CcCLzO5U1/IuzXV5bSoC8Nd58wFzfZbt3uZogvqaCK9iDez6ojbPBjcXHpM+oEYxI3MQxQo6UGBCd6uhEfjKX02GLVAY5zucQujqqRVZWnWwt3BHHzfW8NF7XBp0bYDTAgmVOhBW6I+bQPmC7mJiffnhaM/V6yQINc9wdAMAePAVA7X0AkmKgD8779lvorAegzTifUQXx8uqabH3UT5uTUavMO+WH+utpYH7gKxmO5kO1L6Efut42QknNfAgmqzRqbTpGdgk8jqs0BOjNcMJ0kJeWDJeEMtiYRm64l/CPy2OC6WU2xipfVYr30r2s/LDFUHfvwvSSkiZTFhmj9PtJzjrmbIvEcd9hnYuqf19U89IKMJ2G31Z/hql0dzTJ0Rbk5ElgRvp4b0vnVwyjmp0=
#         'on':
#           tags: false
#           condition: $TRAVIS_PYTHON_VERSION = "3.8"
#           all_branches: true
#       if: "${{ github.event_name == 'push' && $TRAVIS_PYTHON_VERSION == '3.8' && !${{ github.ref }} }}"
    - run: codecov
      if: "${{ success() }}"
  Release:
    needs:
    - test
    - Test_Release
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.8'
    - run: pip install -r requirements.txt
    - run: pip install -r tests/requirements.txt
    - run: python setup.py -q install
    - run: nosetests --with-coverage --cover-package=btcde
#     # This item has no matching transformer
#     - pypi:
#         provider: pypi
#         user: __token__
#         password:
#           secure: jxdITS0ouAhc0hxp/9W3qLu0KUsXM1+l4dGoSfmSTYchOVyLX79EntXJ+LdaJKpWByASjhjZ/+OZaURjuWtvxZ0PcNjt3ZbvWIJnsq0LQnIs1DdabLpRAu5ZNjcOBb7nUqI9GIUse7b4RlPEFIhd5IjUl6e60UnaHTe3.815GoeYgYgWIngDbjWThWzjxHPr5dT5VhXf8ALZpsDS9NewVSo5ogwArY+Rs1bnYn+F2OddpDZkN91tK15SD1Okwg3VtsDB5HL7NrOmtrP0sbyksBNSflaJ7WBgqTX3.88Q6JfvYQkTHrZovW2eDjap3gMGTGd1ZNJU2R1HQbml7jLJSc1Jq1YvKhxgnVUtPgAHSn6ziWMTTQsN3fs+WG1VMVuDJ3.8A8WbGt2Y9GEPDp+faSXT3MTeF0LNSNcYsSNdiVDxkgzYuAfq3IqnwYv6Ln6wz3EsgjCqE0tS6mfQ/rWF4uOB32CFL8Kz6qhjUgbSufmBIM1c7QdX/6ay/AY+EW6QjKvo0ib2XfGqe3Zf71rHPdt9BjLwd6sEriLHbB7Y2Kp4J4QcBg5w3ZzJch7uTo2Zte6rsmKlrElGfMtQTgbXRtykGlrKZaUzQdfE3pwAqZKRxVv6CXfU7gZ1lVsWVpm0NF+mOhQysdM9QFwjbrAYPdkafuimgi33Za4Ox3RCwxI=
#         'on':
#           tags: true
#           branch: main
#           condition: $TRAVIS_PYTHON_VERSION = "3.8"
#       if: "${{ github.event_name == 'push' && $TRAVIS_PYTHON_VERSION == '3.8' && ${{ github.ref }} }}"
    - run: codecov
      if: "${{ success() }}"
