name: Tufuwu/test2
on:
  push:
    branches:
    - "**/*"
  pull_request:
#   # This item has no matching transformer
#   maximum_number_of_builds: 0
jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      TOXENV: flake8
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: 3.8
    - run: pip install tox
    - run: pip install codecov
    - run: tox
    - run: codecov
      if: "${{ success() }}"
  test_2:
    runs-on: ubuntu-22.04
    env:
      TOXENV: black
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: 3.8
    - run: pip install tox
    - run: pip install codecov
    - run: tox
    - run: codecov
      if: "${{ success() }}"
  test_3:
    runs-on: ubuntu-22.04
    env:
      TOXENV: elasticsearch
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: 3.8
    - run: docker pull elasticsearch:7.3.2
    - run: docker run --name elasticsearch -e "discovery.type=single-node" -p 9200:9200 -d elasticsearch:7.3.2
    - run: docker ps
    - run: sleep 60
    - run: pip install tox
    - run: pip install codecov
    - run: tox
    - run: codecov
      if: "${{ success() }}"
    services:
#       # This item has no matching transformer
#       docker:
