name: Tufuwu/test2
on:
  push:
    branches:
    - "**/*"
  pull_request:
#   # This item has no matching transformer
#   maximum_number_of_builds: 0
jobs:
  Unit_tests:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.8'
    - run: sudo apt-get update
    - run: sudo apt-get -y install verilator libevent-dev libjson-c-dev
    - run: cd ~/
    - run: wget https://raw.githubusercontent.com/enjoy-digital/litex/main/litex_setup.py
    - run: python3 litex_setup.py init install
    - run: cd ${{ github.workspace }}
    - run: python3 setup.py install
    - run: wget https://static.dev.sifive.com/dev-tools/riscv64-unknown-elf-gcc-20171231-x86_64-linux-centos6.tar.gz
    - run: tar -xvf riscv64-unknown-elf-gcc-20171231-x86_64-linux-centos6.tar.gz
    - run: export PATH=$PATH:$PWD/riscv64-unknown-elf-gcc-20171231-x86_64-linux-centos6/bin/
    - run: cd ${{ github.workspace }}
    - run: python setup.py test
