name: Tufuwu/test2
on:
  push:
    branches:
    - "**/*"
  pull_request:
#   # This item has no matching transformer
#   maximum_number_of_builds: 0
jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      TOXENV: py38-django22
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.8'
    - run: pip install tox codecov
    - run: tox
    - run: codecov
      if: "${{ success() }}"
  test_2:
    runs-on: ubuntu-22.04
    env:
      TOXENV: py38-django22,py38-django31,py38-django32
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.8'
    - run: pip install tox codecov
    - run: tox
    - run: codecov
      if: "${{ success() }}"
  test_3:
    runs-on: ubuntu-22.04
    env:
      TOXENV: py38-django22,py38-django31,py38-django32
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.8'
    - run: pip install tox codecov
    - run: tox
    - run: codecov
      if: "${{ success() }}"
  test_4:
    runs-on: ubuntu-22.04
    env:
      TOXENV: lint,py38-django22,py38-django31,py38-django32,coverage
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.8'
    - run: pip install tox codecov
    - run: tox
    - run: codecov
      if: "${{ success() }}"
  test_5:
    runs-on: ubuntu-22.04
    env:
      TOXENV: py39-django22,py39-django31,py39-django32
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.9'
    - run: pip install tox codecov
    - run: tox
    - run: codecov
      if: "${{ success() }}"
