name: Tufuwu/test2
on:
  push:
    branches:
    - "**/*"
  pull_request:
#   # This item has no matching transformer
#   maximum_number_of_builds: 0
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: "${{ matrix.python }}"
#     # This item has no matching transformer
#     - sauce_connect:
#         username: django-star-ratings
#         access_key:
#           secure: o9illUJKqoFj+wPEYCkliyIq0jSWiEGjKys6FfD8qmSNwy7gQ6z8oxFwq0CGPROn3aeSJ/tkjSEqQ9pI9RevfhaRoShYImPzvLmRboikzFpLpEVDLJW69im1ZNpQ4P2NUZNx+gQRW3d+Ebh9EbXhyhCPR+ug+jXmJZz/fWRAb/AJiiqiuzgdH82ZwkIgNR8Hfck9UXsvD4hHgbQnEtsAhRwqUcizh+47/xHzCqbCcXZdCSUAsdZ3lVimIsIONZEtCctJ3.8F9MkMgAHGHvblEgFD4TH8kgJXEEcztlt3PipmTlB6YXObxApnYURry9Pr2FU8jzgfIbvhnBgjzpGObXV5H2PYoHl8mnJzjs3OQphpYh4PBpP8rdg5NaR/Dx9w4guCMtnqLA/sL0CbUGek4Pl7dwyXGCV7OXPX7FYqQWoIfROZn7bYbqnJlwVb1pEWZhILVIfE1o/8JtlOlzUzqdCgxGelhFzCN/9BVOUqyhcLYC9iKOnHPudryqeJwans1KUrJkJQzWbcqBqV7mKflpKbRmLLoVgu1eIIeUj7j4225yrfRwEP4z58LWWXMZNzuZ+EsVujhZ1II7sT2vUCAMMcPnfluWkwHsr6LWaqggm91G2dsPLA3XXSB1JbiWGYo9uPfzAromUXoxnIzUZx9gpR1+e121pmpNJ+AM+AjLQ=
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: pip install pip -U
    - run: pip install codecov
    - run: grep -v "^django==" requirements.txt > /tmp/reqs.txt
    - run: pip install -r /tmp/reqs.txt
    - run: pip install "$DJANGO_VERSION" -U
    - run: "./scripts/ci_runtests.sh"
#     # This item has no matching transformer
#     - pypi:
#         provider: pypi
#         user: wildfish-deployer
#         password:
#           secure: HUz4ZGenh+gtXB5DPTtlDvFg4mJKQ6HDgp27Ciq5AqggcU5RmE2b+CCbJhDur540l4OW+kL5jO+NN9bZEkk8E/T4rBuwnn92mTOqsrvBoXHGhhXMuD8L8MH+MyHSCa56Tqsihar5SWbqUekz4SNF9DVP9sEvuatrcI4xMPPvp5TMWozMKy26fm8IQop25bKBUyLA1oUmkfar5kmsNFp5WrIWjbLppOgSNmVTZDZW8xltVXHwc9itE56gM6PICZSd9sUiS/MngjhUdBLa7eJKNkWM4CK0tWl9ABpIfohAHXPEzMO9zUgtj3zM6fmx0sRoee3YijoDPsvU1kBSWPCmshkwn8s+RCP0Y6fMEZFbVzO3qlkQMdFu5Xv3eiOoWocjZrWZtfQlWU+qlBb1CnJDbjkNnaGx/EVPOP9gvid0/YnUXGx79sjBkxgcTLhF+53krh4tGHDJUB6wsI8qi+32Q+smcOQJBbiyGgEyvAalV2NkLqGdEbRiUNa64ek7yRGNMkw5melWlQNFBfKNe9/kKjK799EHsHau9PyYYdZskdtBu+nhz5FE64l1CvgVY/IdY/1MyM+yAQflsV3rvuYeMls1BfM6F1uC7ubVciRuIzIoKhHcXfktjArLUaVe4DcKvSmAeK6lKAu+YMN946Rb07HchPr5m/QHaklggf9Bb4o=
#         'on':
#           tags: true
#           distributions: sdist bdist_wheel
#           repo: wildfish/django-star-ratings
#           condition: "$DEPLOY = true"
#       if: "${{ github.event_name == 'push' && $DEPLOY == true && ${{ github.ref }} }}"
    - run: codecov
      if: "${{ success() }}"
    - uses: rtCamp/action-slack-notify@v2.2.1
      env:
        SLACK_WEBHOOK: "${{ secrets.SLACK_WEBHOOK }}"
    strategy:
      matrix:
        python:
        - '3.8'
        - '3.8'
        - '3.8'
        include:
        - DJANGO_VERSION: Django>=3.0,<3.1
          RUN_WEB_TESTS: 'true'
          BROWSER_TAG: chrome_latest
          DEPLOY: 'true'
          USE_CUSTOM_MODEL: 'true'
        - DJANGO_VERSION: Django>=3.0,<3.1
          RUN_WEB_TESTS: 'true'
          BROWSER_TAG: chrome_latest
          USE_CUSTOM_MODEL: 'false'
        - DJANGO_VERSION: Django>=3.0,<3.1
          RUN_WEB_TESTS: 'false'
          USE_CUSTOM_MODEL: 'true'
        - DJANGO_VERSION: Django>=2.2,<2.3
          RUN_WEB_TESTS: 'false'
          USE_CUSTOM_MODEL: 'true'
        - DJANGO_VERSION: Django>=3.0,<3.1
          RUN_WEB_TESTS: 'false'
          USE_CUSTOM_MODEL: 'false'
        - DJANGO_VERSION: Django>=2.2,<2.3
          RUN_WEB_TESTS: 'false'
          USE_CUSTOM_MODEL: 'false'
        exclude:
        - DJANGO_VERSION: Django>=3.0,<3.1
          RUN_WEB_TESTS: 'false'
          USE_CUSTOM_MODEL: 'true'
          python: '3.8'
        - DJANGO_VERSION: Django>=3.0,<3.1
          RUN_WEB_TESTS: 'false'
          USE_CUSTOM_MODEL: 'false'
          python: '3.8'
        - DJANGO_VERSION: Django>=3.0,<3.1
          RUN_WEB_TESTS: 'true'
          BROWSER_TAG: chrome_latest
          DEPLOY: 'true'
          USE_CUSTOM_MODEL: 'true'
          python: '3.8'
        - DJANGO_VERSION: Django>=3.0,<3.1
          RUN_WEB_TESTS: 'true'
          BROWSER_TAG: chrome_latest
          USE_CUSTOM_MODEL: 'false'
          python: '3.8'
        - DJANGO_VERSION: Django>=3.0,<3.1
          RUN_WEB_TESTS: 'true'
          BROWSER_TAG: chrome_latest
          DEPLOY: 'true'
          USE_CUSTOM_MODEL: 'true'
          python: '3.8'
        - DJANGO_VERSION: Django>=3.0,<3.1
          RUN_WEB_TESTS: 'true'
          BROWSER_TAG: chrome_latest
          USE_CUSTOM_MODEL: 'false'
          python: '3.8'
    env:
      DJANGO_VERSION: "${{ matrix.DJANGO_VERSION }}"
      RUN_WEB_TESTS: "${{ matrix.RUN_WEB_TESTS }}"
      BROWSER_TAG: "${{ matrix.BROWSER_TAG }}"
      DEPLOY: "${{ matrix.DEPLOY }}"
      USE_CUSTOM_MODEL: "${{ matrix.USE_CUSTOM_MODEL }}"
