name: Tufuwu/test2
on:
  push:
    branches:
    - "**/*"
  pull_request:
#   # This item has no matching transformer
#   maximum_number_of_builds: 0
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: "${{ matrix.python }}"
    - name: Set up pip cache
      uses: actions/cache@v3.3.2
      with:
        path: "~/.cache/pip"
        key: "${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}"
        restore-keys: "${{ runner.os }}-pip-"
    - run: apt-get update && apt-get -y install gcc libhdf5-serial-dev libblas-dev liblapack-dev libatlas-base-dev libquadmath0
    - run: python -m pip install --upgrade pip
    - run: pip install -U numpy Cython
    - run: pip install h5py$H5PY_VERSION
    - run: pip install -r requirements_tests.txt
    - run: pip install .
    - run: pip install -e examples/example_hdf5storage_marshaller_plugin
    - run: pytest
#     # This item has no matching transformer
#     - email: false
    strategy:
      matrix:
        H5PY_VERSION:
        - "==3.8"
        - "==2.10"
        - "==3.0"
        - "==3.1"
        python:
        - '3.8'
        - '3.8'
        - '3.9'
        exclude:
        - H5PY_VERSION: "==3.0"
          python: '3.8'
        - H5PY_VERSION: "==3.1"
          python: '3.8'
    env:
      H5PY_VERSION: "${{ matrix.H5PY_VERSION }}"
  test_2:
    runs-on: ubuntu-22.04
    env:
      H5PY_VERSION: "==2.10"
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Set up pip cache
      uses: actions/cache@v3.3.2
      with:
        path: "~/.cache/pip"
        key: "${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}"
        restore-keys: "${{ runner.os }}-pip-"
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.9'
    - run: apt-get update && apt-get -y install gcc libhdf5-serial-dev libblas-dev liblapack-dev libatlas-base-dev libquadmath0
    - run: python -m pip install --upgrade pip
    - run: pip install -U numpy Cython
    - run: pip install h5py$H5PY_VERSION
    - run: pip install -r requirements_tests.txt
    - run: pip install .
    - run: pip install -e examples/example_hdf5storage_marshaller_plugin
    - run: pytest
#     # This item has no matching transformer
#     - email: false
