name: Tufuwu/test2
on:
  push:
    branches:
    - "**/*"
  pull_request:
#   # This item has no matching transformer
#   maximum_number_of_builds: 0
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Set up pip cache
      uses: actions/cache@v3.3.2
      with:
        path: "~/.cache/pip"
        key: "${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}"
        restore-keys: "${{ runner.os }}-pip-"
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.8'
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: pip install tox-travis codecov
    - run: tox -v
    - run: codecov
      if: "${{ success() }}"
#     # This item has no matching transformer
#     - email: false
#     # There was an internal error transforming this item
#     # Message: Failed to transform item
#     - irc:
#         if: branch = main
#         channels:
#         - secure: JDbizbq58cmpQ3hbq9/PT4V0mns9jJ9oa/fF9P/e3raZkqm3APDcfVx79QiIDXShFsy4DYYZDTTPn4yuGhzX29Wo5z0ncWmMaPJP1+BnKxgh1Zit8TcG0doFXjc5A3RRXAEYRkb4ffwJtmWor/hN8fRwFFivg6yH/54I/XWUT12/nlXaMG+hygndkI9Rmg9REVd4/sScBR25xBh6bkTcG/szMZugpvJeZsbjjxaXrZxo3.80wvdiUHGaGffgEVhCHuMMN8bs/5qeM1GMGohQVwqXciBZKUJ51C3YQl61O09SoJxPOjvik+6Os2iiQBkMmKiPTLpvpeXZMDVXM3tVUiLHckmSnuT6FHI4lmpNl0/qPGGlmvNL7PeUuZ+Mcry8meeSwM/3nYSAp4UZC4lojiR221fHIQiT67yUOAYxyaDoTs33QWQT8VE1FkY81DBB+pdcm2E1pgzfTLLTvprEZL+vabVr2ayvvQnTnTg8FKkulLFYDu0IZ3.88+TDULLkPfEUTQMVxq1Xv5cBza1USnF/Mee3x3I8niiHEaC2fDuNRENdQv6hMqcocHy7QiWTPACI/PJjO1CuYfN0QPpuHemxxyZSLrLy7kAnmmcMgUGCnorWcruc53FImsSZzFVAwe8th2iFgHKDPjlWFwB9xjCfgzNpGal85q8S6dVex1E=
#         on_cancel: never
#         on_success: never
#         on_failure: always
  test_2:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Set up pip cache
      uses: actions/cache@v3.3.2
      with:
        path: "~/.cache/pip"
        key: "${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}"
        restore-keys: "${{ runner.os }}-pip-"
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.8'
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: pip install tox-travis codecov
    - run: tox -v
    - run: codecov
      if: "${{ success() }}"
#     # This item has no matching transformer
#     - email: false
#     # There was an internal error transforming this item
#     # Message: Failed to transform item
#     - irc:
#         if: branch = main
#         channels:
#         - secure: JDbizbq58cmpQ3hbq9/PT4V0mns9jJ9oa/fF9P/e3raZkqm3APDcfVx79QiIDXShFsy4DYYZDTTPn4yuGhzX29Wo5z0ncWmMaPJP1+BnKxgh1Zit8TcG0doFXjc5A3RRXAEYRkb4ffwJtmWor/hN8fRwFFivg6yH/54I/XWUT12/nlXaMG+hygndkI9Rmg9REVd4/sScBR25xBh6bkTcG/szMZugpvJeZsbjjxaXrZxo3.80wvdiUHGaGffgEVhCHuMMN8bs/5qeM1GMGohQVwqXciBZKUJ51C3YQl61O09SoJxPOjvik+6Os2iiQBkMmKiPTLpvpeXZMDVXM3tVUiLHckmSnuT6FHI4lmpNl0/qPGGlmvNL7PeUuZ+Mcry8meeSwM/3nYSAp4UZC4lojiR221fHIQiT67yUOAYxyaDoTs33QWQT8VE1FkY81DBB+pdcm2E1pgzfTLLTvprEZL+vabVr2ayvvQnTnTg8FKkulLFYDu0IZ3.88+TDULLkPfEUTQMVxq1Xv5cBza1USnF/Mee3x3I8niiHEaC2fDuNRENdQv6hMqcocHy7QiWTPACI/PJjO1CuYfN0QPpuHemxxyZSLrLy7kAnmmcMgUGCnorWcruc53FImsSZzFVAwe8th2iFgHKDPjlWFwB9xjCfgzNpGal85q8S6dVex1E=
#         on_cancel: never
#         on_success: never
#         on_failure: always
  test_3:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Set up pip cache
      uses: actions/cache@v3.3.2
      with:
        path: "~/.cache/pip"
        key: "${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}"
        restore-keys: "${{ runner.os }}-pip-"
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.8'
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: pip install tox-travis codecov
    - run: tox -v
    - run: codecov
      if: "${{ success() }}"
#     # This item has no matching transformer
#     - email: false
#     # There was an internal error transforming this item
#     # Message: Failed to transform item
#     - irc:
#         if: branch = main
#         channels:
#         - secure: JDbizbq58cmpQ3hbq9/PT4V0mns9jJ9oa/fF9P/e3raZkqm3APDcfVx79QiIDXShFsy4DYYZDTTPn4yuGhzX29Wo5z0ncWmMaPJP1+BnKxgh1Zit8TcG0doFXjc5A3RRXAEYRkb4ffwJtmWor/hN8fRwFFivg6yH/54I/XWUT12/nlXaMG+hygndkI9Rmg9REVd4/sScBR25xBh6bkTcG/szMZugpvJeZsbjjxaXrZxo3.80wvdiUHGaGffgEVhCHuMMN8bs/5qeM1GMGohQVwqXciBZKUJ51C3YQl61O09SoJxPOjvik+6Os2iiQBkMmKiPTLpvpeXZMDVXM3tVUiLHckmSnuT6FHI4lmpNl0/qPGGlmvNL7PeUuZ+Mcry8meeSwM/3nYSAp4UZC4lojiR221fHIQiT67yUOAYxyaDoTs33QWQT8VE1FkY81DBB+pdcm2E1pgzfTLLTvprEZL+vabVr2ayvvQnTnTg8FKkulLFYDu0IZ3.88+TDULLkPfEUTQMVxq1Xv5cBza1USnF/Mee3x3I8niiHEaC2fDuNRENdQv6hMqcocHy7QiWTPACI/PJjO1CuYfN0QPpuHemxxyZSLrLy7kAnmmcMgUGCnorWcruc53FImsSZzFVAwe8th2iFgHKDPjlWFwB9xjCfgzNpGal85q8S6dVex1E=
#         on_cancel: never
#         on_success: never
#         on_failure: always
  test_4:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Set up pip cache
      uses: actions/cache@v3.3.2
      with:
        path: "~/.cache/pip"
        key: "${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}"
        restore-keys: "${{ runner.os }}-pip-"
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.9'
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: pip install tox-travis codecov
    - run: tox -v
    - run: codecov
      if: "${{ success() }}"
#     # This item has no matching transformer
#     - email: false
#     # There was an internal error transforming this item
#     # Message: Failed to transform item
#     - irc:
#         if: branch = main
#         channels:
#         - secure: JDbizbq58cmpQ3hbq9/PT4V0mns9jJ9oa/fF9P/e3raZkqm3APDcfVx79QiIDXShFsy4DYYZDTTPn4yuGhzX29Wo5z0ncWmMaPJP1+BnKxgh1Zit8TcG0doFXjc5A3RRXAEYRkb4ffwJtmWor/hN8fRwFFivg6yH/54I/XWUT12/nlXaMG+hygndkI9Rmg9REVd4/sScBR25xBh6bkTcG/szMZugpvJeZsbjjxaXrZxo3.80wvdiUHGaGffgEVhCHuMMN8bs/5qeM1GMGohQVwqXciBZKUJ51C3YQl61O09SoJxPOjvik+6Os2iiQBkMmKiPTLpvpeXZMDVXM3tVUiLHckmSnuT6FHI4lmpNl0/qPGGlmvNL7PeUuZ+Mcry8meeSwM/3nYSAp4UZC4lojiR221fHIQiT67yUOAYxyaDoTs33QWQT8VE1FkY81DBB+pdcm2E1pgzfTLLTvprEZL+vabVr2ayvvQnTnTg8FKkulLFYDu0IZ3.88+TDULLkPfEUTQMVxq1Xv5cBza1USnF/Mee3x3I8niiHEaC2fDuNRENdQv6hMqcocHy7QiWTPACI/PJjO1CuYfN0QPpuHemxxyZSLrLy7kAnmmcMgUGCnorWcruc53FImsSZzFVAwe8th2iFgHKDPjlWFwB9xjCfgzNpGal85q8S6dVex1E=
#         on_cancel: never
#         on_success: never
#         on_failure: always
  test_5:
    runs-on: ubuntu-22.04
    env:
      TOXENV: mypy
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Set up pip cache
      uses: actions/cache@v3.3.2
      with:
        path: "~/.cache/pip"
        key: "${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}"
        restore-keys: "${{ runner.os }}-pip-"
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.9'
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: pip install tox-travis codecov
    - run: tox -v
    - run: codecov
      if: "${{ success() }}"
#     # This item has no matching transformer
#     - email: false
#     # There was an internal error transforming this item
#     # Message: Failed to transform item
#     - irc:
#         if: branch = main
#         channels:
#         - secure: JDbizbq58cmpQ3hbq9/PT4V0mns9jJ9oa/fF9P/e3raZkqm3APDcfVx79QiIDXShFsy4DYYZDTTPn4yuGhzX29Wo5z0ncWmMaPJP1+BnKxgh1Zit8TcG0doFXjc5A3RRXAEYRkb4ffwJtmWor/hN8fRwFFivg6yH/54I/XWUT12/nlXaMG+hygndkI9Rmg9REVd4/sScBR25xBh6bkTcG/szMZugpvJeZsbjjxaXrZxo3.80wvdiUHGaGffgEVhCHuMMN8bs/5qeM1GMGohQVwqXciBZKUJ51C3YQl61O09SoJxPOjvik+6Os2iiQBkMmKiPTLpvpeXZMDVXM3tVUiLHckmSnuT6FHI4lmpNl0/qPGGlmvNL7PeUuZ+Mcry8meeSwM/3nYSAp4UZC4lojiR221fHIQiT67yUOAYxyaDoTs33QWQT8VE1FkY81DBB+pdcm2E1pgzfTLLTvprEZL+vabVr2ayvvQnTnTg8FKkulLFYDu0IZ3.88+TDULLkPfEUTQMVxq1Xv5cBza1USnF/Mee3x3I8niiHEaC2fDuNRENdQv6hMqcocHy7QiWTPACI/PJjO1CuYfN0QPpuHemxxyZSLrLy7kAnmmcMgUGCnorWcruc53FImsSZzFVAwe8th2iFgHKDPjlWFwB9xjCfgzNpGal85q8S6dVex1E=
#         on_cancel: never
#         on_success: never
#         on_failure: always
