name: Tufuwu/test2
on:
  push:
    branches:
    - "**/*"
    - main
  pull_request:
#   # This item has no matching transformer
#   maximum_number_of_builds: 0
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: "${{ matrix.python }}"
    - name: Set up pip cache
      uses: actions/cache@v3.3.2
      with:
        path: "~/.cache/pip"
        key: "${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}"
        restore-keys: "${{ runner.os }}-pip-"
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: pip install codecov
    - run: pip install -U pip wheel setuptools
    - run: pip install $PACKAGES -e .[tests]
    - run: coverage run --rcfile=.coveragerc runtests.py
    - run: codecov
      if: "${{ success() }}"
    - uses: rectalogic/notify-irc@v1
      if: "${{ github.event_name != 'pull_request' }}"
      with:
        server: irc.freenode.org
        port: 6697
        channel: django-fluent
        nickname: Default nickname
        message: "%{repository}#%{build_number} (%{commit}) %{message}  --  %{build_url}"
#     # This item has no matching transformer
#     - email:
#         recipients:
#         - travis@edoburu.nl
#         on_success: never
#         on_failure: always
    - uses: rtCamp/action-slack-notify@v2.2.1
      if: "${{ failure() }}"
      env:
        SLACK_WEBHOOK: "${{ secrets.SLACK_WEBHOOK }}"
    strategy:
      matrix:
        PACKAGES:
        - django>=1.11,<1.12
        - django>=2.0,<2.1
        python:
        - '3.8'
        - '3.8'
        - '3.8'
        exclude:
        - PACKAGES: django>=2.0,<2.1
          python: '3.8'
#       # 'allow_failures' transformations are currently unsupported.
    env:
      PACKAGES: "${{ matrix.PACKAGES }}"
  test_2:
    runs-on: ubuntu-22.04
    env:
      PACKAGES: django>=2.1,<2.2
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Set up pip cache
      uses: actions/cache@v3.3.2
      with:
        path: "~/.cache/pip"
        key: "${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}"
        restore-keys: "${{ runner.os }}-pip-"
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.8'
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: pip install codecov
    - run: pip install -U pip wheel setuptools
    - run: pip install $PACKAGES -e .[tests]
    - run: coverage run --rcfile=.coveragerc runtests.py
    - run: codecov
      if: "${{ success() }}"
    - uses: rectalogic/notify-irc@v1
      if: "${{ github.event_name != 'pull_request' }}"
      with:
        server: irc.freenode.org
        port: 6697
        channel: django-fluent
        nickname: Default nickname
        message: "%{repository}#%{build_number} (%{commit}) %{message}  --  %{build_url}"
#     # This item has no matching transformer
#     - email:
#         recipients:
#         - travis@edoburu.nl
#         on_success: never
#         on_failure: always
    - uses: rtCamp/action-slack-notify@v2.2.1
      if: "${{ failure() }}"
      env:
        SLACK_WEBHOOK: "${{ secrets.SLACK_WEBHOOK }}"
  test_3:
    runs-on: ubuntu-22.04
    env:
      PACKAGES: django>=2.2,<2.3
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Set up pip cache
      uses: actions/cache@v3.3.2
      with:
        path: "~/.cache/pip"
        key: "${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}"
        restore-keys: "${{ runner.os }}-pip-"
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.8'
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: pip install codecov
    - run: pip install -U pip wheel setuptools
    - run: pip install $PACKAGES -e .[tests]
    - run: coverage run --rcfile=.coveragerc runtests.py
    - run: codecov
      if: "${{ success() }}"
    - uses: rectalogic/notify-irc@v1
      if: "${{ github.event_name != 'pull_request' }}"
      with:
        server: irc.freenode.org
        port: 6697
        channel: django-fluent
        nickname: Default nickname
        message: "%{repository}#%{build_number} (%{commit}) %{message}  --  %{build_url}"
#     # This item has no matching transformer
#     - email:
#         recipients:
#         - travis@edoburu.nl
#         on_success: never
#         on_failure: always
    - uses: rtCamp/action-slack-notify@v2.2.1
      if: "${{ failure() }}"
      env:
        SLACK_WEBHOOK: "${{ secrets.SLACK_WEBHOOK }}"
  test_4:
    runs-on: ubuntu-22.04
    env:
      PACKAGES: django>=3.0,<3.1
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Set up pip cache
      uses: actions/cache@v3.3.2
      with:
        path: "~/.cache/pip"
        key: "${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}"
        restore-keys: "${{ runner.os }}-pip-"
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.8'
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: pip install codecov
    - run: pip install -U pip wheel setuptools
    - run: pip install $PACKAGES -e .[tests]
    - run: coverage run --rcfile=.coveragerc runtests.py
    - run: codecov
      if: "${{ success() }}"
    - uses: rectalogic/notify-irc@v1
      if: "${{ github.event_name != 'pull_request' }}"
      with:
        server: irc.freenode.org
        port: 6697
        channel: django-fluent
        nickname: Default nickname
        message: "%{repository}#%{build_number} (%{commit}) %{message}  --  %{build_url}"
#     # This item has no matching transformer
#     - email:
#         recipients:
#         - travis@edoburu.nl
#         on_success: never
#         on_failure: always
    - uses: rtCamp/action-slack-notify@v2.2.1
      if: "${{ failure() }}"
      env:
        SLACK_WEBHOOK: "${{ secrets.SLACK_WEBHOOK }}"
