name: Tufuwu/test2
on:
  push:
    branches:
    - "**/*"
  pull_request:
#   # This item has no matching transformer
#   maximum_number_of_builds: 0
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: "${{ matrix.python }}"
    - name: Set up pip cache
      uses: actions/cache@v3.3.2
      with:
        path: "~/.cache/pip"
        key: "${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}"
        restore-keys: "${{ runner.os }}-pip-"
    - run: pip install -U pip
    - run: pip install -U setuptools
    - run: pip install -U wheel
    - run: pip install -r test-requirements.txt
    - run: pip install tox-travis .[devel]
    - run: tox
    - run: python setup.py install
    - run: niet project.meta.name tests/samples/sample.yaml
    - run: niet .project.meta.name tests/samples/sample.yaml
    - run: niet project.list tests/samples/sample.yaml
    - run: niet .project.list tests/samples/sample.json
    - run: niet . tests/samples/sample.json
    - run: niet -f squote project.list tests/samples/sample.yaml
    - run: niet -f squote project.meta.name tests/samples/sample.yaml
    - run: niet -f dquote project.list tests/samples/sample.yaml
    - run: niet -f dquote project.meta.name tests/samples/sample.yaml
    - run: niet -f ifs project.list tests/samples/sample.yaml
    - run: niet --format newline project.list tests/samples/sample.yaml
    - run: niet --format yaml project.list tests/samples/sample.yaml
    - run: niet --format json project.list tests/samples/sample.yaml
    - run: niet project.'"test-dash"' tests/samples/sample.yaml
    - run: niet project.'"test-dash"' tests/samples/sample.json
    - run: niet project.'"test-dash"' tests/samples/sample.json -f eval
    - run: niet project.list tests/samples/sample.json -f eval
    - run: niet project tests/samples/sample.json -f eval
    - run: eval $(niet project tests/samples/sample.json -f eval) && test "${project__foo}" = "bar"
    - run: niet -f yaml .project tests/samples/sample.yaml -o test.yaml && test -f test.yaml && ! grep '^project:$' test.yaml
    - run: cp test.yaml test.old.yaml && niet -f yaml .list test.yaml -i && ! diff test.old.yaml
    - run: niet -f yaml .project tests/samples/sample.yaml --output test2.yaml && test -f test2.yaml && ! grep '^project:$' test2.yaml
    - run: cp test2.yaml test2.old.yaml && niet -f yaml .list test2.yaml --in-place && ! diff test2.old.yaml
#     # This item has no matching transformer
#     - pypi:
#         provider: pypi
#         user: 4383
#         password:
#           secure: f6/SMklCR7Jvf9epmOrpaK3bfb0EETi5LvPVWYj+PLLgUUImNAuQKA3QCNn7I5/+efd1nqZQ3cerQLjVhgAzNZI07Bguc7FGuadePulphpD0CEg7O5WRhqz9KxMurJO1Dje05nYqrFhHFyJZCiXcmHAAoBEFEM8v0TkuVzBIRgtYV4o6ySRFWnwx3a9vybl0l+jUVGufv+sDAo6OozlvVQQK+Z2xFiCz9ePee4RD/LvxAxxgzC5726/56tXuxRxd8fUgtIOCCNutBkewSTo4JXzYUK9bpvQ01pk+b9fkgNDcC+xmXxozhEksZMDyBvQN6tpj0+AYjuZCSu+RQwOHXZ0V2syCjQF3gGNCy7LxQd2/alpDWTIGMPtwR5XvP8ic3UsXpbF9N546IraMc7rm/cBr0U1SdepXO65zSBFxVDOTbXTBnfeNGY8V2dG/9R89RwC9YHFeRf1KjqP8rACC/41eAHn/tB0+WGvcAaXV5snUKZXXetShjGxC78rcSwR1y++HkRbI88o3LqnVjwBaiwAUKKcXLSaS9XLg9+KNBIYb0vzvZaFDh1WxYUwdRgJG/MUZlii8X3CERNPgHxl8mC4yTAITWE1ModnZB+8+Re/63OZB+O88htvHxt8GL2hhU/YH8riwAy2sjSu312U0CMHlzMa18JiLtI1NvTnCHl0=
#         'on':
#           tags: true
#         distributions: sdist bdist_wheel
#       if: "${{ github.event_name == 'push' && ${{ github.ref }} }}"
    strategy:
      matrix:
        python:
        - '3.8'
        - '3.8'
        - '3.8'
        - 3.8
