name: Tufuwu/test2
on:
  push:
    branches:
    - "**/*"
  pull_request:
#   # This item has no matching transformer
#   maximum_number_of_builds: 0
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: "${{ matrix.python }}"
    - run: sudo apt-get -qq update
    - run: sudo apt-get install -y graphviz python-tk python-matplotlib
    - run: travis_retry pip install Sphinx
    - run: travis_retry pip install recommonmark
    - run: travis_retry pip install pep8
    - run: travis_retry pip install coverage
    - run: travis_retry pip install coveralls
    - run: travis_retry pip install numpy
    - run: python -Wall setup.py try
    - run: python setup.py install
    - run: python -Wall setup.py test
    - run: COVERAGE=1 coverage run test/runtest.py
    - run: python run.py --doctest
    - run: python run.py --html
    - run: pep8 --exclude=asizeof.py,metadata.py,bottle*.py --max-line-length=80 pympler
    - run: coveralls
      if: "${{ success() }}"
    strategy:
      matrix:
        python:
        - '3.8'
        - '3.8'
        - '3.8'
        - '3.8'
        - '3.8'
        - 3.8
