name: Tufuwu/test2
on:
  push:
    branches:
    - "**/*"
  pull_request:
#   # This item has no matching transformer
#   maximum_number_of_builds: 0
jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      TOX_ENV: py38
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - run: rm -rf ${{ github.workspace }}/.cache/pip/log
    - name: Set up cache
      uses: actions/cache@v3.3.2
      with:
        path: "${{ github.workspace }}/.cache/pip"
        key: "${{ runner.os }}-path"
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: 3.8.12
    - run: pip install -U -r requirements-dev.txt
    - run: pip install .
    - run: tox -e $TOX_ENV
    - run: pytest --dead-fixtures
  test_2:
    runs-on: ubuntu-22.04
    env:
      TOX_ENV: py38
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - run: rm -rf ${{ github.workspace }}/.cache/pip/log
    - name: Set up cache
      uses: actions/cache@v3.3.2
      with:
        path: "${{ github.workspace }}/.cache/pip"
        key: "${{ runner.os }}-path"
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: 3.8.9
    - run: pip install -U -r requirements-dev.txt
    - run: pip install .
    - run: tox -e $TOX_ENV
    - run: pytest --dead-fixtures
  test_3:
    runs-on: ubuntu-22.04
    env:
      TOX_ENV: py38
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - run: rm -rf ${{ github.workspace }}/.cache/pip/log
    - name: Set up cache
      uses: actions/cache@v3.3.2
      with:
        path: "${{ github.workspace }}/.cache/pip"
        key: "${{ runner.os }}-path"
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: 3.8.6
    - run: pip install -U -r requirements-dev.txt
    - run: pip install .
    - run: tox -e $TOX_ENV
    - run: pytest --dead-fixtures
  test_4:
    runs-on: ubuntu-22.04
    env:
      TOX_ENV: py39
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - run: rm -rf ${{ github.workspace }}/.cache/pip/log
    - name: Set up cache
      uses: actions/cache@v3.3.2
      with:
        path: "${{ github.workspace }}/.cache/pip"
        key: "${{ runner.os }}-path"
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: 3.9.1
    - run: pip install -U -r requirements-dev.txt
    - run: pip install .
    - run: tox -e $TOX_ENV
    - run: pytest --dead-fixtures
  test_5:
    runs-on: ubuntu-22.04
    env:
      TOX_ENV: pypy-3.6
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - run: rm -rf ${{ github.workspace }}/.cache/pip/log
    - name: Set up cache
      uses: actions/cache@v3.3.2
      with:
        path: "${{ github.workspace }}/.cache/pip"
        key: "${{ runner.os }}-path"
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: pypy-3.6
    - run: pip install -U -r requirements-dev.txt
    - run: pip install .
    - run: tox -e $TOX_ENV
    - run: pytest --dead-fixtures
  test_6:
    runs-on: ubuntu-22.04
    env:
      TOX_ENV: lint
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - run: rm -rf ${{ github.workspace }}/.cache/pip/log
    - name: Set up cache
      uses: actions/cache@v3.3.2
      with:
        path: "${{ github.workspace }}/.cache/pip"
        key: "${{ runner.os }}-path"
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: 3.9.1
    - run: pip install -U -r requirements-dev.txt
    - run: pip install .
    - run: tox -e $TOX_ENV
    - run: pytest --dead-fixtures
