name: Tufuwu/test2
on:
  push:
    branches:
    - "**/*"
  pull_request:
#   # This item has no matching transformer
#   maximum_number_of_builds: 0
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: if [ "$WITH_OPT_DEPS" = "true" ] ; then pip install -vr requirements.txt pytest; fi
    - run: git clone https://github.com/ProgVal/irctest.git
    - run: echo "y" | pip uninstall limnoria || true
    - run: echo $TRAVIS_PYTHON_VERSION
    - run: python setup.py install
    - run: supybot-test test -v --plugins-dir=./plugins/ --no-network
    - run: if [ "$WITH_OPT_DEPS" = "true" ] -a [[ "$TRAVIS_PYTHON_VERSION" =~ ^3\.[4-9] ]] ; then cd irctest; pytest --controllers irctest.controllers.limnoria; fi
#     # This item has no matching transformer
#     - email: false
    strategy:
      matrix: {}
#       # 'allow_failures' transformations are currently unsupported.
  test_2:
    runs-on: # this agent type is not supported: [[{"dist"=>"trusty"}]]
             ubuntu-latest
    env:
      WITH_OPT_DEPS: 'false'
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.8'
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: if [ "$WITH_OPT_DEPS" = "true" ] ; then pip install -vr requirements.txt pytest; fi
    - run: git clone https://github.com/ProgVal/irctest.git
    - run: echo "y" | pip uninstall limnoria || true
    - run: echo $TRAVIS_PYTHON_VERSION
    - run: python setup.py install
    - run: supybot-test test -v --plugins-dir=./plugins/ --no-network
    - run: if [ "$WITH_OPT_DEPS" = "true" ] -a [[ "$TRAVIS_PYTHON_VERSION" =~ ^3\.[4-9] ]] ; then cd irctest; pytest --controllers irctest.controllers.limnoria; fi
#     # This item has no matching transformer
#     - email: false
  test_3:
    runs-on: # this agent type is not supported: [[{"dist"=>"trusty"}]]
             ubuntu-latest
    env:
      WITH_OPT_DEPS: 'false'
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.8'
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: if [ "$WITH_OPT_DEPS" = "true" ] ; then pip install -vr requirements.txt pytest; fi
    - run: git clone https://github.com/ProgVal/irctest.git
    - run: echo "y" | pip uninstall limnoria || true
    - run: echo $TRAVIS_PYTHON_VERSION
    - run: python setup.py install
    - run: supybot-test test -v --plugins-dir=./plugins/ --no-network
    - run: if [ "$WITH_OPT_DEPS" = "true" ] -a [[ "$TRAVIS_PYTHON_VERSION" =~ ^3\.[4-9] ]] ; then cd irctest; pytest --controllers irctest.controllers.limnoria; fi
#     # This item has no matching transformer
#     - email: false
  test_4:
    runs-on: # this agent type is not supported: [[{"dist"=>"trusty"}]]
             ubuntu-latest
    env:
      WITH_OPT_DEPS: 'false'
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.8'
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: if [ "$WITH_OPT_DEPS" = "true" ] ; then pip install -vr requirements.txt pytest; fi
    - run: git clone https://github.com/ProgVal/irctest.git
    - run: echo "y" | pip uninstall limnoria || true
    - run: echo $TRAVIS_PYTHON_VERSION
    - run: python setup.py install
    - run: supybot-test test -v --plugins-dir=./plugins/ --no-network
    - run: if [ "$WITH_OPT_DEPS" = "true" ] -a [[ "$TRAVIS_PYTHON_VERSION" =~ ^3\.[4-9] ]] ; then cd irctest; pytest --controllers irctest.controllers.limnoria; fi
#     # This item has no matching transformer
#     - email: false
  test_5:
    runs-on: ubuntu-22.04
    env:
      WITH_OPT_DEPS: 'false'
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.8'
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: if [ "$WITH_OPT_DEPS" = "true" ] ; then pip install -vr requirements.txt pytest; fi
    - run: git clone https://github.com/ProgVal/irctest.git
    - run: echo "y" | pip uninstall limnoria || true
    - run: echo $TRAVIS_PYTHON_VERSION
    - run: python setup.py install
    - run: supybot-test test -v --plugins-dir=./plugins/ --no-network
    - run: if [ "$WITH_OPT_DEPS" = "true" ] -a [[ "$TRAVIS_PYTHON_VERSION" =~ ^3\.[4-9] ]] ; then cd irctest; pytest --controllers irctest.controllers.limnoria; fi
#     # This item has no matching transformer
#     - email: false
  test_6:
    runs-on: ubuntu-22.04
    env:
      WITH_OPT_DEPS: 'true'
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.8'
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: if [ "$WITH_OPT_DEPS" = "true" ] ; then pip install -vr requirements.txt pytest; fi
    - run: git clone https://github.com/ProgVal/irctest.git
    - run: echo "y" | pip uninstall limnoria || true
    - run: echo $TRAVIS_PYTHON_VERSION
    - run: python setup.py install
    - run: supybot-test test -v --plugins-dir=./plugins/ --no-network
    - run: if [ "$WITH_OPT_DEPS" = "true" ] -a [[ "$TRAVIS_PYTHON_VERSION" =~ ^3\.[4-9] ]] ; then cd irctest; pytest --controllers irctest.controllers.limnoria; fi
#     # This item has no matching transformer
#     - email: false
  test_7:
    runs-on: ubuntu-22.04
    env:
      WITH_OPT_DEPS: 'true'
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.8'
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: if [ "$WITH_OPT_DEPS" = "true" ] ; then pip install -vr requirements.txt pytest; fi
    - run: git clone https://github.com/ProgVal/irctest.git
    - run: echo "y" | pip uninstall limnoria || true
    - run: echo $TRAVIS_PYTHON_VERSION
    - run: python setup.py install
    - run: supybot-test test -v --plugins-dir=./plugins/ --no-network
    - run: if [ "$WITH_OPT_DEPS" = "true" ] -a [[ "$TRAVIS_PYTHON_VERSION" =~ ^3\.[4-9] ]] ; then cd irctest; pytest --controllers irctest.controllers.limnoria; fi
#     # This item has no matching transformer
#     - email: false
  test_8:
    runs-on: ubuntu-22.04
    env:
      WITH_OPT_DEPS: 'true'
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.9'
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: if [ "$WITH_OPT_DEPS" = "true" ] ; then pip install -vr requirements.txt pytest; fi
    - run: git clone https://github.com/ProgVal/irctest.git
    - run: echo "y" | pip uninstall limnoria || true
    - run: echo $TRAVIS_PYTHON_VERSION
    - run: python setup.py install
    - run: supybot-test test -v --plugins-dir=./plugins/ --no-network
    - run: if [ "$WITH_OPT_DEPS" = "true" ] -a [[ "$TRAVIS_PYTHON_VERSION" =~ ^3\.[4-9] ]] ; then cd irctest; pytest --controllers irctest.controllers.limnoria; fi
#     # This item has no matching transformer
#     - email: false
  test_9:
    runs-on: ubuntu-22.04
    env:
      WITH_OPT_DEPS: 'true'
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: 3.8
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: if [ "$WITH_OPT_DEPS" = "true" ] ; then pip install -vr requirements.txt pytest; fi
    - run: git clone https://github.com/ProgVal/irctest.git
    - run: echo "y" | pip uninstall limnoria || true
    - run: echo $TRAVIS_PYTHON_VERSION
    - run: python setup.py install
    - run: supybot-test test -v --plugins-dir=./plugins/ --no-network
    - run: if [ "$WITH_OPT_DEPS" = "true" ] -a [[ "$TRAVIS_PYTHON_VERSION" =~ ^3\.[4-9] ]] ; then cd irctest; pytest --controllers irctest.controllers.limnoria; fi
#     # This item has no matching transformer
#     - email: false
  test_10:
    runs-on: # this agent type is not supported: [[{"dist"=>"trusty"}]]
             ubuntu-latest
    env:
      WITH_OPT_DEPS: 'false'
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: pypy-3.6
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: if [ "$WITH_OPT_DEPS" = "true" ] ; then pip install -vr requirements.txt pytest; fi
    - run: git clone https://github.com/ProgVal/irctest.git
    - run: echo "y" | pip uninstall limnoria || true
    - run: echo $TRAVIS_PYTHON_VERSION
    - run: python setup.py install
    - run: supybot-test test -v --plugins-dir=./plugins/ --no-network
    - run: if [ "$WITH_OPT_DEPS" = "true" ] -a [[ "$TRAVIS_PYTHON_VERSION" =~ ^3\.[4-9] ]] ; then cd irctest; pytest --controllers irctest.controllers.limnoria; fi
#     # This item has no matching transformer
#     - email: false
  test_11:
    runs-on: ubuntu-22.04
    env:
      WITH_OPT_DEPS: 'true'
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: 3.8
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: if [ "$WITH_OPT_DEPS" = "true" ] ; then pip install -vr requirements.txt pytest; fi
    - run: git clone https://github.com/ProgVal/irctest.git
    - run: echo "y" | pip uninstall limnoria || true
    - run: echo $TRAVIS_PYTHON_VERSION
    - run: python setup.py install
    - run: supybot-test test -v --plugins-dir=./plugins/ --no-network
    - run: if [ "$WITH_OPT_DEPS" = "true" ] -a [[ "$TRAVIS_PYTHON_VERSION" =~ ^3\.[4-9] ]] ; then cd irctest; pytest --controllers irctest.controllers.limnoria; fi
#     # This item has no matching transformer
#     - email: false
