name: Tufuwu/test2
on:
  push:
    branches:
    - "**/*"
  pull_request:
#   # This item has no matching transformer
#   maximum_number_of_builds: 0
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.8'
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: pip install ".[build]"
    - run: tox
#     # This item has no matching transformer
#     - pypi:
#         provider: pypi
#         user: __token__
#         password: "$PYPI_TOKEN"
#         distributions: sdist bdist_wheel
#         skip_cleanup: true
#         skip_existing: true
#         'on':
#           tags: true
#           condition: "$PYPI_TOKEN"
#       if: "${{ github.event_name == 'push' && $PYPI_TOKEN && ${{ github.ref }} }}"
#     # This item has no matching transformer
#     - pypi:
#         provider: pypi
#         user: __token__
#         password: "$PYPI_TOKEN"
#         distributions: sdist bdist_wheel
#         skip_cleanup: true
#         skip_existing: true
#         'on':
#           branch: dev
#           condition: "$PYPI_TOKEN"
#       if: "${{ github.event_name == 'push' && $PYPI_TOKEN && github.ref == 'refs/heads/dev' }}"
    - run: if [[ $TOXENV == *"coverage"* ]]; then coveralls; fi
      if: "${{ success() }}"
  test_2:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.8'
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: pip install ".[build]"
    - run: tox
#     # This item has no matching transformer
#     - pypi:
#         provider: pypi
#         user: __token__
#         password: "$PYPI_TOKEN"
#         distributions: sdist bdist_wheel
#         skip_cleanup: true
#         skip_existing: true
#         'on':
#           tags: true
#           condition: "$PYPI_TOKEN"
#       if: "${{ github.event_name == 'push' && $PYPI_TOKEN && ${{ github.ref }} }}"
#     # This item has no matching transformer
#     - pypi:
#         provider: pypi
#         user: __token__
#         password: "$PYPI_TOKEN"
#         distributions: sdist bdist_wheel
#         skip_cleanup: true
#         skip_existing: true
#         'on':
#           branch: dev
#           condition: "$PYPI_TOKEN"
#       if: "${{ github.event_name == 'push' && $PYPI_TOKEN && github.ref == 'refs/heads/dev' }}"
    - run: if [[ $TOXENV == *"coverage"* ]]; then coveralls; fi
      if: "${{ success() }}"
  test_3:
    runs-on: ubuntu-22.04
    env:
      TOXENV: coverage,mypy,style,docs,dist-test
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.8'
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: pip install ".[build]"
    - run: tox
#     # This item has no matching transformer
#     - pypi:
#         provider: pypi
#         user: __token__
#         password: "$PYPI_TOKEN"
#         distributions: sdist bdist_wheel
#         skip_cleanup: true
#         skip_existing: true
#         'on':
#           tags: true
#           condition: "$PYPI_TOKEN"
#       if: "${{ github.event_name == 'push' && $PYPI_TOKEN && ${{ github.ref }} }}"
#     # This item has no matching transformer
#     - pypi:
#         provider: pypi
#         user: __token__
#         password: "$PYPI_TOKEN"
#         distributions: sdist bdist_wheel
#         skip_cleanup: true
#         skip_existing: true
#         'on':
#           branch: dev
#           condition: "$PYPI_TOKEN"
#       if: "${{ github.event_name == 'push' && $PYPI_TOKEN && github.ref == 'refs/heads/dev' }}"
    - run: if [[ $TOXENV == *"coverage"* ]]; then coveralls; fi
      if: "${{ success() }}"
  test_4:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.8'
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: pip install ".[build]"
    - run: tox
#     # This item has no matching transformer
#     - pypi:
#         provider: pypi
#         user: __token__
#         password: "$PYPI_TOKEN"
#         distributions: sdist bdist_wheel
#         skip_cleanup: true
#         skip_existing: true
#         'on':
#           tags: true
#           condition: "$PYPI_TOKEN"
#       if: "${{ github.event_name == 'push' && $PYPI_TOKEN && ${{ github.ref }} }}"
#     # This item has no matching transformer
#     - pypi:
#         provider: pypi
#         user: __token__
#         password: "$PYPI_TOKEN"
#         distributions: sdist bdist_wheel
#         skip_cleanup: true
#         skip_existing: true
#         'on':
#           branch: dev
#           condition: "$PYPI_TOKEN"
#       if: "${{ github.event_name == 'push' && $PYPI_TOKEN && github.ref == 'refs/heads/dev' }}"
    - run: if [[ $TOXENV == *"coverage"* ]]; then coveralls; fi
      if: "${{ success() }}"
  test_5:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.9'
#     # 'sudo' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: pip install ".[build]"
    - run: tox
#     # This item has no matching transformer
#     - pypi:
#         provider: pypi
#         user: __token__
#         password: "$PYPI_TOKEN"
#         distributions: sdist bdist_wheel
#         skip_cleanup: true
#         skip_existing: true
#         'on':
#           tags: true
#           condition: "$PYPI_TOKEN"
#       if: "${{ github.event_name == 'push' && $PYPI_TOKEN && ${{ github.ref }} }}"
#     # This item has no matching transformer
#     - pypi:
#         provider: pypi
#         user: __token__
#         password: "$PYPI_TOKEN"
#         distributions: sdist bdist_wheel
#         skip_cleanup: true
#         skip_existing: true
#         'on':
#           branch: dev
#           condition: "$PYPI_TOKEN"
#       if: "${{ github.event_name == 'push' && $PYPI_TOKEN && github.ref == 'refs/heads/dev' }}"
    - run: if [[ $TOXENV == *"coverage"* ]]; then coveralls; fi
      if: "${{ success() }}"
